import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Botones from "@/components/Botones"
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Adolf.dev | Portafolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es" className='scroll-smooth'>
      <body className='scroll-smooth'>
        {children}
        <Botones />
        </body>
    </html>
  )
}
